# Generated by Django 2.2.7 on 2021-10-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('ph_no', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('cus_type', models.CharField(choices=[('NC', 'New Customer'), ('EC', 'Exist Customer')], default='New Customer', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('ph_no', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('emp_type', models.CharField(choices=[('EM', 'Manager'), ('ES', 'Staff'), ('EA', 'Admin')], default='Staff', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('ph_no', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('ven_type', models.CharField(choices=[('NV', 'New Vendor'), ('EV', 'Exist Vendor')], default='New Vendor', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
