# Generated by Django 2.2.7 on 2021-10-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cus_type',
            field=models.CharField(choices=[('NC', 'New Customer'), ('Exist Customer', 'Exist Customer')], default='New Customer', max_length=2),
        ),
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Staff', max_length=2),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='ven_type',
            field=models.CharField(choices=[('New Vendor', 'New Vendor'), ('Exist Vendor', 'Exist Vendor')], default='New Vendor', max_length=2),
        ),
    ]
