# Generated by Django 2.2.7 on 2021-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0003_auto_20211001_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cus_type',
            field=models.CharField(choices=[('New Customer', 'New Customer'), ('Exist Customer', 'Exist Customer')], default='New Customer', max_length=20),
        ),
    ]
